[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "day-01"
path = "main.rs"
